import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Navbar from "./components/organisms/Navbar";
import NotificationModal from "./components/organisms/NotificationModal";
import PostModal from "./components/organisms/PostModal";
import { getAuthenticatedUser } from "@/lib/services/user";
import { getNotifications } from "@/lib/services/notifications";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getAuthenticatedUser();
  const notifications = await getNotifications(user?.id!);
  const notificationCount = notifications.filter((a) => {
    return a.seen === false;
  }).length;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar
          showNotificationIcon={notificationCount > 0}
          notificationCount={notificationCount}
        />
        <PostModal />
        <NotificationModal notifications={notifications} />
        {children}
      </body>
    </html>
  );
}
